In [1]:
import numpy as np
import pandas as pd
from scipy.stats import kurtosis, skew, zscore

### What does df.melt do?

In [2]:
df = pd.DataFrame(
    {
        "Name": {0: "John", 1: "Bob", 2: "Shiela"},
        "Course": {0: "Masters", 1: "Graduate", 2: "Graduate"},
        "Age": {0: 27, 1: 23, 2: 21},
    }
)
example = pd.melt(df, id_vars=["Name", "Age"], value_vars=["Course"])
example

Name  Age variable     value
0    John   27   Course   Masters
1     Bob   23   Course  Graduate
2  Shiela   21   Course  Graduate

In [3]:
df = pd.DataFrame(
    {
        "Name": ["John", "Bob", "Shiela", "John", "Bob", "Shiela"],
        "Course": [
            "Masters",
            "Graduate",
            "Graduate",
            "Masters",
            "Graduate",
            "Graduate",
        ],
        "Age": [21, 27, 31, 21, 27, 31],
        "OlderAge": [41, 47, 49, 41, 49, 51],
    }
)
df

Name    Course  Age  OlderAge
0    John   Masters   21        41
1     Bob  Graduate   27        47
2  Shiela  Graduate   31        49
3    John   Masters   21        41
4     Bob  Graduate   27        49
5  Shiela  Graduate   31        51

### What is the purpose of melt?
- The idea is that if you have two columns that are the same, you can add them together.

In [4]:
df_melt = df.melt(
    id_vars=["Course"],
    value_vars=["Age", "OlderAge"],
    value_name="NumericalAgeValue",
    var_name="AllAges",
)
df_melt

Course   AllAges  NumericalAgeValue
0    Masters       Age                 21
1   Graduate       Age                 27
2   Graduate       Age                 31
3    Masters       Age                 21
4   Graduate       Age                 27
5   Graduate       Age                 31
6    Masters  OlderAge                 41
7   Graduate  OlderAge                 47
8   Graduate  OlderAge                 49
9    Masters  OlderAge                 41
10  Graduate  OlderAge                 49
11  Graduate  OlderAge                 51

In [5]:
data = [
    [5, 3, 3, 7, 3],  # Row 0
    [5, 3, 3, 8, 3],  # No Big Change
    [5, 3, 3, 9, 3],  # No Big Change
    [5, 4, 4, 7, 4],  # Change
]
z_scores = np.abs(zscore(data, axis=1))
z_scores

array([[0.5       , 0.75      , 0.75      , 1.75      , 0.75      ],
       [0.30618622, 0.71443451, 0.71443451, 1.83711731, 0.71443451],
       [0.17149859, 0.68599434, 0.68599434, 1.88648444, 0.68599434],
       [0.17149859, 0.68599434, 0.68599434, 1.88648444, 0.68599434]])

In [6]:
threshold = 9
z_scores = [
    [0.1, 0.5, 15.0, 0.3],  # Row 0 (Value 15.0 is > 9)
    [0.2, 0.4, 0.5, 0.1],  # Row 1
    [0.2, 0.4, 0.5, 0.1],  # Row 2
]
outlier_rows = np.where(np.max(z_scores, axis=1) > threshold)[0]
outlier_rows

array([0])

In [7]:
data = [[5, 2, 2, 7, 2], [5, 3, 3, 7, 3], [5, 4, 4, 7, 4]]
df = pd.DataFrame(data)
mean_signals = df.mean(axis=0)
mean_signals

0    5.0
1    3.0
2    3.0
3    7.0
4    3.0
dtype: float64

In [8]:
data = np.array(data)
e = data**2
f = np.sum(e, axis=1)
data

array([[5, 2, 2, 7, 2],
       [5, 3, 3, 7, 3],
       [5, 4, 4, 7, 4]])

In [9]:
e

array([[25,  4,  4, 49,  4],
       [25,  9,  9, 49,  9],
       [25, 16, 16, 49, 16]])

In [10]:
f

array([ 86, 101, 122])

In [88]:
data = [[1, 5, 3, 4, 5, 7], [9, 7, 3, 2, 1, 1], [2, 3, 4, 4, 3, 3]]
d = np.array(data)
lists = np.diff(d, axis=1)
lists

array([[ 4, -2,  1,  1,  2],
       [-2, -4, -1, -1,  0],
       [ 1,  1,  0, -1,  0]])

In [89]:
dx = np.mean(lists, axis=1)
dx

array([ 1.2, -1.6,  0.2])

In [82]:
signal = np.array([[3, 10, 9, 8, 4, 3, 9], [7, 10, 9, 8, 6, 7, 9]])
minus = signal.mean(axis=1, keepdims=True)
minus

array([[6.57142857],
       [8.        ]])

In [39]:
signal_centered = signal - minus
signal_centered

array([[-3.57142857,  3.42857143,  2.42857143,  1.42857143, -2.57142857,
        -3.57142857,  2.42857143],
       [-1.        ,  2.        ,  1.        ,  0.        , -2.        ,
        -1.        ,  1.        ]])

In [40]:
sign = np.sign(signal_centered)
sign

array([[-1.,  1.,  1.,  1., -1., -1.,  1.],
       [-1.,  1.,  1.,  0., -1., -1.,  1.]])

In [65]:
signals = np.array([[10, 12, 10, 8, 10], [100, 105, 95, 100, 105]])
minus = signals.mean(axis=1)
minus

array([ 10., 101.])

In [53]:
centered_signals = signals - signals.mean(axis=1, keepdims=True)
centered_signals

array([[ 0.,  2.,  0., -2.,  0.],
       [-1.,  4., -6., -1.,  4.]])

In [61]:
signed = np.sign(centered_signals)
signed

array([[ 0.,  1.,  0., -1.,  0.],
       [-1.,  1., -1., -1.,  1.]])

In [62]:
cross = signed >= 0
cross

array([[ True,  True,  True, False,  True],
       [False,  True, False, False,  True]])

In [60]:
difference_adjacent = np.diff(cross, axis=1)
difference_adjacent

array([[False, False,  True,  True],
       [ True,  True, False,  True]])

In [64]:
sums = np.sum(difference_adjacent, axis=1)
sums

array([2, 3])

array([[ True,  True,  True,  True],
       [ True,  True, False,  True]])